export const FOLDER_CREATE_SUCCESS = 'FOLDER_CREATE_SUCCESS';
export const FOLDER_SAVE_REQUEST = 'FOLDER_SAVE_REQUEST';
export const FOLDER_SAVE_SUCCESS = 'FOLDER_SAVE_SUCCESS';
export const FOLDER_SAVE_FAIL = 'FOLDER_SAVE_FAIL';

export const FOLDER_LIST_REQUEST = 'FOLDER_LIST_REQUEST';
export const FOLDER_LIST_SUCCESS = 'FOLDER_LIST_SUCCESS';
export const FOLDER_LIST_FAIL = 'FOLDER_LIST_FAIL';

export const FOLDER_LIST_USER_REQUEST = 'FOLDER_LIST_USER_REQUEST';
export const FOLDER_LIST_USER_SUCCESS = 'FOLDER_LIST_USER_SUCCESS';
export const FOLDER_LIST_USER_FAIL = 'FOLDER_LIST_USER_FAIL';

export const FOLDER_DETAILS_REQUEST = 'FOLDER_DETAILS_REQUEST';
export const FOLDER_DETAILS_SUCCESS = 'FOLDER_DETAILS_SUCCESS';
export const FOLDER_DETAILS_FAIL = 'FOLDER_DETAILS_FAIL';

export const FOLDER_DELETE_REQUEST = 'FOLDER_DELETE_REQUEST';
export const FOLDER_DELETE_SUCCESS = 'FOLDER_DELETE_SUCCESS';
export const FOLDER_DELETE_FAIL = 'FOLDER_DELETE_FAIL';
