export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_SAVE_REQUEST = 'NOTE_SAVE_REQUEST';
export const NOTE_SAVE_SUCCESS = 'NOTE_SAVE_SUCCESS';
export const NOTE_SAVE_FAIL = 'NOTE_SAVE_FAIL';

export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';

export const NOTE_LIST_USER_REQUEST = 'NOTE_LIST_USER_REQUEST';
export const NOTE_LIST_USER_SUCCESS = 'NOTE_LIST_USER_SUCCESS';
export const NOTE_LIST_USER_FAIL = 'NOTE_LIST_USER_FAIL';

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST';
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS';
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL';

export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST';
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS';
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL';
